import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  skillButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    margin: 0,
    padding: '1px 10px 1px 10px',
    color: '#aaa',
    '&:hover': {
      color: '#444',
    },
  },
  loginButton: {
    fontFamily: `'Courier Prime', monospace`,
    cursor: 'pointer',
    padding: '1px 20px 1px 20px',
    borderRadius: 2,
    color: '#aaa',
    height: 40,
    border: '1px solid rgba(0,0,0,0.1)',
    boxShadow: '0 0 3px rgba(255,255,255,1), inset 0 0 3px rgba(255,255,255,1)',
    background: 'none',
    margin: 3,
    '&:hover': {
      color: '#777',
      border: '1px solid #bdfd1d',
      borderBottom: '1px solid #ade71b',
      borderRight: '1px solid #ade71b',
    },
  },
  registerButton: {
    fontFamily: `'Courier Prime', monospace`,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '1px 10px 1px 10px',
    color: '#aaa',
    height: 40,
    margin: 3,
    '&:hover': {
      color: '#444',
    },
  },
  saveButton: {
    fontFamily: `'Courier Prime', monospace`,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    margin: '0 0 5px 0',
    color: '#aaa',
    width: 60,
    '&:hover': {
      color: '#444',
    },
  },
  input: {
    fontFamily: `'Courier Prime', monospace`,
    fontSize: '0.8rem',
    padding: 4,
    margin: 3,
    height: 32,
    color: '#222',
    boxShadow: 'inset 2px 2px 5px rgba(0,0,0,0.05)',
    background: '#fff',
    border: '1px solid rgba(0,0,0,0.1)',
    '&:hover': {
      border: '1px solid #bdfd1d',
    },
  },
  inputDate: {
    fontFamily: `'Courier Prime', monospace`,
    fontSize: '0.8rem',
    padding: 4,
    border: 'none',
    margin: 3,
    width: 100,
    background: '#444',
    color: '#fff',
  },
  inputDetails: {
    fontFamily: `'Courier Prime', monospace`,
    fontSize: '0.8rem',
    padding: 4,
    border: 'none',
    margin: 3,
    width: 300,
    background: '#444',
    color: '#fff',
  },
  divider: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    borderBottom: '1px dashed #aaa',
    alignItems: 'center',
  },
  dividerLine: {
    width: '100%',
    borderBottom: '1px dashed #aaa',
  },
  inner: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    boxShadow: '0px 0px 20px rgba(0,0,0,0.05)',
    border: '1px solid rgba(0,0,0,0.05)',
    background: '#f6f5f3',
  },
}));
